name: DeityProtect
main: com.imdeity.protect.DeityProtect
version: 12.08.07.02
language: english.yml
author: vanZeben
website: http://dev.bukkit.org/server-mods/deityprotect
depend: [DeityAPI]
commands:
    DeityProtect:
        aliases: []
    Regen:
        aliases: []